module.exports = {
  file: 'Guide-Gestion-CRM-CECHEMOI.docx',
  kicker: 'Guide pratique',
  title: 'Gérer la relation client',
  subtitle: 'Pour l’assistante de gestion : clients, commandes atelier, stock, caisse, messages et anniversaires',
  version: 'Version 1 — octobre 2026',
  blocks: [
    // ------------------------------------------------------------------
    { h1: 'Se connecter et s’orienter', lead: 'L’adresse, l’accueil et les sept rubriques' },
    { p: 'L’espace de gestion s’ouvre dans un navigateur (Chrome conseillé), sur ordinateur comme sur téléphone, à l’adresse **https://gestion.cechemoi.com**.' },
    { steps: [
      'Saisissez votre **Email** et votre **Mot de passe** personnels.',
      'Cochez **Se souvenir de moi** uniquement sur un appareil qui ne sert qu’à vous.',
      'Cliquez sur **Se connecter**. En cas d’oubli, utilisez **Mot de passe oublié ?**.',
    ] },
    { img: '00-login.png', cap: 'Page de connexion — gestion.cechemoi.com', width: 520 },
    { p: 'La page d’accueil présente vos rubriques sous forme de grandes tuiles. Cliquez sur une tuile pour ouvrir ses actions.' },
    { img: 'C01-accueil.png', cap: 'Page d’accueil de l’espace de gestion' },
    { table: { widths: [2600, 6760], head: ['Tuile', 'À quoi elle sert'], rows: [
      ['**Clients**', 'Ajouter une cliente, retrouver sa fiche, lui écrire (chapitre 2).'],
      ['**Commandes atelier**', 'Commandes sur mesure, suivi de confection, acomptes ; la facture est créée automatiquement (chapitre 3).'],
      ['**Boutique en ligne**', 'Le site cechemoi.com et les ventes au comptoir. Rubrique couverte par le guide « Gérer la boutique en ligne ».'],
      ['**Stock matériels**', 'Tissus et fournitures de l’atelier : entrées, sorties, fiches par couturier (chapitre 4).'],
      ['**Caisse**', 'Dépenses du jour, reçus et factures (chapitre 5).'],
      ['**Messages**', 'SMS et WhatsApp à une cliente ou à toutes (chapitre 6).'],
      ['**Anniversaires**', 'Vœux automatiques envoyés aux clientes (chapitre 7).'],
    ] } },
    { note: { title: 'La barre du haut, toujours visible', text: [
      '**Accueil** ramène à cette page depuis n’importe quel écran.',
      '**Rechercher…** retrouve en quelques lettres une cliente, une commande ou une facture.',
      'L’icône lune passe en **mode sombre** ; l’icône à droite de votre prénom vous **déconnecte**.',
    ] } },
    { warn: { title: 'Vos identifiants sont personnels', text: 'Chaque action est enregistrée à votre nom (« Fiche créée par… »). Ne prêtez jamais votre accès et déconnectez-vous sur un ordinateur partagé.' } },

    // ------------------------------------------------------------------
    { h1: 'Clients', lead: 'Ajouter, retrouver et contacter les clientes' },
    { img: 'C02-clients-hub.png', cap: 'Rubrique Clients' },
    { h2: 'Ajouter une cliente' },
    { p: 'Chemin : **Clients → Ajouter un client**. Seuls le **prénom** et le **téléphone** sont obligatoires ; complétez le reste dès que possible.' },
    { img: 'C03-client-nouveau.png', cap: 'Formulaire « Nouveau Client »' },
    { steps: [
      '**Prénom** (obligatoire) et **Nom** (facultatif si la cliente n’a qu’un seul nom).',
      '**Téléphone** (obligatoire) : vérifiez le drapeau du pays (+225 pour la Côte d’Ivoire), puis tapez le numéro **sans l’indicatif**.',
      '**WhatsApp** : seulement s’il diffère du téléphone principal.',
      '**Date d’anniversaire** au format JJ-MM-AAAA (ex. 30-06-1983). Sans elle, la cliente ne recevra pas ses vœux automatiques.',
      '**Comment avez-vous connu CÈCHÉMOI ?** : demandez-le toujours, la direction s’en sert pour sa publicité.',
      'Ouvrez les sections facultatives si besoin : **Mensurations**, **Localisation**, **Adresse de livraison**, **Notes**.',
      '**Notifications de bienvenue** : laissez SMS + WhatsApp activés pour que la cliente reçoive le message d’accueil.',
      'Cliquez sur **Créer le Client**.',
    ] },
    { h3: 'Saisir les mensurations' },
    { img: 'C04-client-mensurations.png', cap: 'Section « Mensurations » dépliée' },
    { steps: [
      'Cliquez sur **Mensurations** pour déplier le tableau.',
      'Vérifiez la **Date des mensurations** et l’**Unité** (centimètres par défaut).',
      'Remplissez chaque ligne mesurée (dos, carrure, épaule, poitrine, tour de taille, bassin, longueurs de manches…). Laissez vide ce qui n’a pas été mesuré.',
    ] },
    { note: { text: 'Les mensurations peuvent aussi être ajoutées plus tard depuis la fiche de la cliente. Chaque prise de mesures est datée : à la commande, vous choisirez la plus récente.' } },
    { h2: 'Retrouver une cliente' },
    { p: 'Chemin : **Clients → Tous les clients**.' },
    { img: 'C05-clients-liste.png', cap: 'Liste des clientes (noms et numéros d’exemple)' },
    { bullets: [
      'Tapez un **nom, un téléphone ou un email** dans la recherche.',
      'Le filtre **segments** isole les clientes VIP, Haute valeur, Actives, Nouvelles ou Inactives ; **Filtrer par date** retrouve les inscriptions d’une période.',
      'Les icônes de la colonne **Actions** : **œil** (fiche), **crayon** (modifier), **document** (fiche PDF).',
    ] },
    { warn: { text: 'Ne supprimez jamais une cliente (icône corbeille) : son historique de commandes et de factures disparaîtrait. Signalez les doublons à la direction.' } },
    { h2: 'La fiche cliente' },
    { img: 'C06-client-fiche.jpg', cap: 'Haut de la fiche : coordonnées et chiffres clés' },
    { bullets: [
      'En haut à droite : **Modifier**, **Nouvelle commande**, **Nouvelle facture**.',
      'Au centre : coordonnées, date d’inscription, nombre de commandes et montant des achats.',
      'Plus bas : **historique des commandes**, **mensurations** et **notes**.',
    ] },
    { img: 'C07-client-fiche-bas.jpg', cap: 'Bas de la fiche : mensurations, notes et envoi rapide' },
    { bullets: [
      '**Notes** : **Privée** reste interne à l’équipe ; **Partagée** envoie aussi une notification à la cliente. Choisissez avant de cliquer sur **Ajouter la note**.',
      '**Envoi rapide** : choisissez le canal (WhatsApp ou SMS), écrivez le message et cliquez sur **Envoyer**.',
    ] },
    { h2: 'Écrire à une cliente (WhatsApp ou SMS)' },
    { p: 'Chemin : **Clients → Envoyer un WhatsApp** (ou **Envoyer un SMS**). Les deux écrans fonctionnent de la même façon.' },
    { img: 'C09-whatsapp-composer.jpg', cap: 'Cliente sélectionnée, zone de message et historique WhatsApp' },
    { steps: [
      'Dans **Sélectionner un client**, tapez le nom ou le numéro, puis cliquez sur la cliente.',
      'L’**historique** des messages déjà envoyés s’affiche à droite : relisez-le pour ne pas vous répéter.',
      'Écrivez votre message dans **Composer le message**. Les **variables** (ex. {customer_name}) insèrent automatiquement le nom de la cliente.',
      'Cliquez sur **Envoyer sur WhatsApp** (ou **Envoyer le SMS**). Le message de succès confirme l’envoi.',
    ] },
    { note: { title: 'Un bon message WhatsApp', text: 'Court, poli, signé CÈCHÉMOI. Trois ou quatre lignes au plus ; *astérisques* pour le gras. Une tenue prête ? Indiquez la date et les horaires de retrait.' } },

    // ------------------------------------------------------------------
    { h1: 'Commandes atelier (sur mesure)', lead: 'De la prise de commande à la livraison' },
    { img: 'C10-atelier-hub.jpg', cap: 'Rubrique Commandes atelier' },
    { note: { title: 'Automatique dès la création', text: [
      'La **facture est générée automatiquement** : ne créez pas de facture à part dans la caisse.',
      'La cliente est **notifiée** à chaque étape clé (en production, essayage, prête, livrée).',
      'Les **acomptes** et les **sorties de matériel** s’enregistrent ensuite depuis la fiche de la commande.',
    ] } },
    { h2: 'Créer une commande sur mesure' },
    { p: 'Chemin : **Commandes atelier → Nouvelle commande**.' },
    { img: 'C11-atelier-nouvelle-haut.png', cap: 'Haut du formulaire : rappel des automatismes et choix de la cliente' },
    { steps: [
      '**Client** : tapez le nom ou le téléphone et choisissez la cliente. Si elle n’existe pas, le lien **Créer un nouveau client** ouvre le formulaire d’ajout.',
      '**Mensurations** : choisissez la prise de mesures datée qui convient, ou « Sans mensurations ».',
    ] },
    { img: 'C12-atelier-articles.png', cap: 'Bloc « Articles » : une ligne par tenue commandée' },
    { steps: [
      '**Type de tenue** (obligatoire) : Boubou, Robe de soirée, Ensemble tunique, Tailleur, Caftan… ou **Autre**, en précisant le modèle.',
      '**Quantité** et **Prix unitaire (FCFA)** : le sous-total se calcule seul.',
      '**Couturier assigné** : le chiffre entre parenthèses indique combien de tenues il a déjà en cours. Répartissez la charge.',
      '**Estimation approximative (en heures)** et **Description** : couleur, tissu, style, détails particuliers.',
      'Plusieurs tenues ? Cliquez sur **Ajouter un article** pour chaque pièce supplémentaire.',
    ] },
    { img: 'C13-atelier-dates-recap.png', cap: 'Dates, récapitulatif et notifications' },
    { steps: [
      '**Date de retrait** (obligatoire) : la date promise à la cliente.',
      '**Délai client** (facultatif) : l’événement de la cliente (mariage, cérémonie), pour que l’atelier connaisse la vraie limite.',
      'Contrôlez le **Récapitulatif** (coût des tenues, total).',
      '**Notes** : informations internes pour l’atelier.',
      '**Notifications** : laissez SMS et WhatsApp cochés ; la cliente reçoit le lien de sa facture.',
      'Cliquez sur **Créer la Commande**.',
    ] },
    { h2: 'Suivre les commandes' },
    { p: 'Chemin : **Commandes atelier → Toutes les commandes**.' },
    { img: 'C14-atelier-liste.png', cap: 'Liste des commandes sur mesure' },
    { bullets: [
      'Les **cases de statut** (En attente, En production, Essayage, Retouches, Prêt, Livré, Annulé) filtrent la liste d’un clic.',
      'La recherche fonctionne par **numéro**, **nom** ou **téléphone** ; le filtre **priorité** isole les commandes urgentes ou VIP.',
      'Les colonnes **Avance** et **Reliquat** montrent ce qui a été payé et ce qui reste dû.',
      'L’**œil** ouvre la commande, l’icône verte télécharge sa fiche PDF.',
    ] },
    { h2: 'La fiche d’une commande' },
    { img: 'C15-atelier-fiche.png', cap: 'Fiche d’une commande sur mesure' },
    { bullets: [
      'Boutons du haut : **Voir la facture**, **Fiche de suivi** (pour l’atelier), **Fiche PDF**.',
      'Un bandeau rouge signale un **retrait en retard**.',
      'Quatre chiffres : **Total**, **Payé**, **Reliquat**, date de **Retrait**.',
      'Onglet **Articles** : pour chaque tenue, changez le **couturier** et l’**étape** de confection.',
      'Onglets **Paiements**, **Matériels**, **Fichiers** (photos de modèle, croquis), **Historique** et **Notes**.',
      'À droite, **Statut de la commande** : choisissez la nouvelle étape, la cliente est prévenue automatiquement.',
    ] },
    { h3: 'Enregistrer un acompte ou un paiement' },
    { img: 'C16-atelier-paiement.png', cap: 'Fenêtre « Ajouter un paiement »' },
    { steps: [
      'Sur la fiche, cliquez sur **Ajouter un paiement**.',
      'Saisissez le **Montant (FCFA)** reçu.',
      'Choisissez le **Mode de paiement** : Espèces, Orange Money, MTN MoMo, Wave, Carte bancaire ou Virement.',
      'Vérifiez la **Date du paiement**, ajoutez une note si besoin (ex. « acompte 50 % »), puis **Enregistrer**.',
      'Le **Payé** et le **Reliquat** se mettent à jour, ainsi que la facture liée.',
    ] },
    { h3: 'Enregistrer les matériels utilisés' },
    { img: 'C17-atelier-materiels.png', cap: 'Onglet « Matériels » de la commande' },
    { p: 'Onglet **Matériels → Enregistrer une sortie** : le tissu et les fournitures prélevés sont rattachés à la commande et déduits du stock. Le détail de la sortie est expliqué au chapitre 4.' },
    { h2: 'Suivi de production' },
    { p: 'Chemin : **Commandes atelier → Suivi de production**. C’est la vue de l’atelier, article par article.' },
    { img: 'C18-production.png', cap: 'Tableau de production (noms de clientes d’exemple)' },
    { steps: [
      'Choisissez une **étape** dans la colonne de gauche : En attente, Coupe, Couture, Essayage, Retouches, Finitions, Terminé.',
      'Filtrez si besoin par **couturier**.',
      'Sur chaque carte, changez directement le **Couturier** ou l’**Étape** : l’enregistrement est immédiat.',
      'Les dates de retrait **en rouge** sont dépassées : relancez l’atelier et prévenez la cliente.',
    ] },
    { h2: 'Fiche de suivi confection' },
    { p: 'Chemin : **Commandes atelier → Fiche de suivi confection**. Recherchez la commande et cliquez sur **Télécharger** pour imprimer la fiche remise au couturier.' },
    { img: 'C19-fiche-suivi-confection.png', cap: 'Liste des fiches de suivi' },

    // ------------------------------------------------------------------
    { h1: 'Stock matériels', lead: 'Tissus et fournitures de l’atelier' },
    { img: 'C20-stock-hub.png', cap: 'Rubrique Stock matériels' },
    { warn: { title: 'Un mouvement de stock ne se modifie pas', text: 'Vérifiez les quantités avant de valider. En cas d’erreur, utilisez **Corriger** dans **Mouvements** : le stock est rectifié par un ajustement et l’historique reste intact.' } },
    { h2: 'Sortie de stock' },
    { p: 'Chemin : **Stock matériels → Sortie de stock**. Une seule saisie peut regrouper tous les matériels d’une tenue : tissu, fil, boutons, fermeture, dentelle, doublure…' },
    { img: 'C21-stock-sortie.png', cap: 'Formulaire « Sortie de Matériel »' },
    { steps: [
      '**Commande sur mesure** : choisissez la commande concernée (facultatif, mais fortement conseillé).',
      '**Matériel #1** : choisissez le matériel et indiquez la quantité.',
      'Cliquez sur **Ajouter un matériel** pour chaque fourniture supplémentaire.',
      '**Couturier (qui a demandé)** : indispensable pour la fiche de sortie par couturier.',
      '**Date** : laissez vide pour maintenant. Ajoutez une note si utile, puis **Enregistrer les sorties**.',
    ] },
    { h2: 'Entrée de stock' },
    { p: 'Chemin : **Stock matériels → Entrée de stock**, à chaque achat ou livraison de fournitures.' },
    { img: 'C22-stock-entree.png', cap: 'Formulaire « Entrée de Matériel »' },
    { steps: [
      '**Matériel** : choisissez-le dans la liste. S’il n’existe pas, créez-le d’abord (Nouveau matériel).',
      '**Quantité reçue** et **Prix unitaire d’achat (CFA)**.',
      '**N° Référence / Bon de commande** et **Notes** si vous les avez.',
      'Cliquez sur **Enregistrer l’entrée**.',
    ] },
    { h2: 'Tous les matériels' },
    { img: 'C23-stock-liste.jpg', cap: 'Liste des matériels et niveaux de stock' },
    { bullets: [
      'Recherchez par **nom, SKU ou fournisseur**, filtrez par **catégorie**.',
      'Cochez **Stock bas uniquement** pour la liste des achats à prévoir.',
      'Sur chaque ligne : entrée, sortie, modification.',
    ] },
    { h2: 'Nouveau matériel' },
    { img: 'C24-stock-nouveau-materiel.jpg', cap: 'Formulaire « Nouveau Matériel »' },
    { steps: [
      '**Nom du matériel** (ex. Wax hollandais bleu), **Catégorie** et **Unité** (mètre, pièce, bobine, rouleau…) sont obligatoires.',
      '**Prix unitaire** et **Stock initial** : ce que vous avez réellement en main aujourd’hui.',
      '**Seuil d’alerte stock bas** : en dessous, le matériel est signalé.',
      '**Fournisseur**, **Couleur**, **Description** : facultatifs mais utiles pour racheter le même article.',
      'Cliquez sur **Enregistrer**.',
    ] },
    { h2: 'Mouvements et fiche par couturier' },
    { img: 'C25-stock-mouvements.jpg', cap: 'Historique des mouvements' },
    { bullets: [
      '**Mouvements** : toutes les entrées et sorties, filtrables par type, matériel, couturier et période. Le lien **Corriger** rectifie une erreur.',
      '**Fiche de sortie par couturier** : choisissez le couturier et la période (Du / Au), puis **Imprimer la fiche**. Elle récapitule ce que chacun a pris.',
    ] },
    { img: 'C26-stock-fiche-couturier.jpg', cap: 'Fiche de sortie par couturier' },

    // ------------------------------------------------------------------
    { h1: 'Caisse', lead: 'Dépenses du jour, reçus et factures' },
    { img: 'C27-caisse-hub.jpg', cap: 'Rubrique Caisse' },
    { warn: { title: 'Ne créez pas de facture depuis la caisse', text: 'Une facture naît d’une commande. Pour facturer une cliente, créez sa **commande atelier** (ou sa vente au comptoir) : la facture est générée automatiquement.' } },
    { h2: 'Ajouter une dépense' },
    { p: 'Chemin : **Caisse → Ajouter une dépense**, le jour même de la dépense.' },
    { img: 'C28-depense-nouvelle.jpg', cap: 'Formulaire « Nouvelle Dépense »' },
    { steps: [
      '**Catégorie** : choisissez la plus précise (ex. Électricité (CIE), Eau (SODECI), Wifi facture, Achat de pagnes…).',
      '**Description** : ce qui a été payé, avec la période (ex. « Facture électricité septembre 2026 »).',
      '**Montant (CFA)** et **Mode de paiement** (Espèces, Orange Money, Wave…).',
      '**Date de paiement** : aujourd’hui par défaut. **Référence / N° facture** : le numéro du reçu fournisseur.',
      'Cliquez sur **Enregistrer la dépense** et gardez le justificatif papier.',
    ] },
    { h2: 'Consulter' },
    { img: 'C29-depenses-liste.jpg', cap: '« Toutes les dépenses » : vos propres saisies' },
    { bullets: [
      '**Toutes les dépenses** affiche les dépenses que **vous** avez saisies, avec filtres par catégorie, mode de paiement et dates.',
      '**Reçus d’aujourd’hui** liste les encaissements du jour. **Voir tous** élargit à toutes les dates.',
      '**Toutes les factures** permet de retrouver une facture par numéro ou par cliente et de suivre son statut (Brouillon, Envoyée, Payée, En retard).',
    ] },
    { img: 'C30-recus-jour.jpg', cap: 'Reçus du jour (montants cumulés masqués sur cette capture)' },
    { img: 'C31-factures.jpg', cap: 'Liste des factures (noms d’exemple)' },

    // ------------------------------------------------------------------
    { h1: 'Messages', lead: 'SMS et WhatsApp, à une cliente ou à toutes' },
    { img: 'C32-messages-hub.jpg', cap: 'Rubrique Messages' },
    { note: { title: 'Ce qui part tout seul', text: 'Les **vœux d’anniversaire** et les **notifications de commande** (en production, tenue prête…) sont envoyés automatiquement. Ne les envoyez pas à la main.' } },
    { p: '**WhatsApp à une cliente** et **SMS à une cliente** : mêmes écrans que dans la rubrique Clients (chapitre 2).' },
    { h2: 'Lancer une campagne WhatsApp' },
    { p: 'Chemin : **Messages → Campagne WhatsApp**. Une campagne n’est lancée que **sur instruction de la direction**.' },
    { img: 'C33-campagne-whatsapp.jpg', cap: 'Préparation d’une campagne WhatsApp, avec aperçu à droite' },
    { steps: [
      '**Nom de la campagne** : pour la retrouver dans les rapports (ex. « Nouvelle collection octobre »).',
      '**Destinataires** : **Tous les clients**, ou **Numéros personnalisés** pour une liste précise.',
      '**Média** (facultatif) : une image ou un PDF de 5 Mo maximum, ou **Parcourir la médiathèque**.',
      '**Message** : jusqu’à 4 096 caractères. Les variables ({customer_name}…) personnalisent chaque envoi. L’aperçu du téléphone montre le rendu.',
      '**Sauvegarder Brouillon** pour faire relire, puis **Envoyer la Campagne** une fois validée.',
    ] },
    { warn: { title: 'Toujours tester avant d’envoyer à toutes', text: 'Faites d’abord un envoi en **Numéros personnalisés** vers votre propre numéro. Un message parti vers plusieurs centaines de clientes ne se rattrape pas.' } },
    { h2: 'Campagne SMS' },
    { p: 'Même fonctionnement que la campagne WhatsApp, sans média. Un SMS compte **160 caractères** ; un message peut aller jusqu’à 5 SMS (800 caractères), facturés chacun. Faites court.' },
    { h2: 'Rapports d’envois' },
    { img: 'C34-rapports-envois.jpg', cap: 'Rapports de campagnes' },
    { p: 'Pour chaque campagne : canal, statut, nombre de messages arrivés sur le nombre envoyé, auteur et date. **Voir** ouvre le détail des échecs. N’utilisez pas **Supprimer** : le rapport sert de preuve d’envoi.' },

    // ------------------------------------------------------------------
    { h1: 'Anniversaires', lead: 'Des vœux envoyés automatiquement chaque matin' },
    { img: 'C35-anniversaires.jpg', cap: 'Prochains anniversaires (noms et numéros d’exemple)' },
    { bullets: [
      'Chaque jour à **8 h**, le système envoie un **SMS et un WhatsApp** aux clientes dont c’est l’anniversaire.',
      'Une cliente reçoit **un seul envoi par an**. Les personnes nées un 29 février sont fêtées le 28 les années non bissextiles.',
      'L’onglet **Prochains anniversaires** liste les envois à venir ; **Historique des envois** montre ce qui est parti ou a échoué.',
    ] },
    { note: { title: 'Votre rôle', text: [
      'Renseigner la **date d’anniversaire** de chaque nouvelle cliente : sans elle, pas de vœux.',
      'Consulter les **échecs** une fois par semaine : un échec signale souvent un numéro erroné. Corrigez-le dans la fiche cliente.',
    ] } },

    // ------------------------------------------------------------------
    { h1: 'Aide-mémoire', lead: 'La routine et les erreurs à éviter' },
    { h2: 'Chaque jour' },
    { bullets: [
      'Créer les nouvelles clientes et les **commandes atelier** du jour, avec acompte si versé.',
      'Ouvrir le **Suivi de production** : mettre à jour les étapes, repérer les retards en rouge.',
      'Enregistrer chaque **paiement** reçu sur la commande concernée.',
      'Enregistrer les **sorties de matériel** au moment où le couturier se sert.',
      'Saisir les **dépenses** du jour dans la Caisse.',
    ] },
    { h2: 'Chaque semaine' },
    { bullets: [
      'Cocher **Stock bas uniquement** dans Tous les matériels et transmettre la liste d’achats.',
      'Vérifier les **échecs d’anniversaire** et corriger les numéros.',
      'Imprimer les **fiches de sortie par couturier** si la direction les demande.',
    ] },
    { h2: 'Erreurs fréquentes' },
    { table: { widths: [4300, 5060], head: ['Situation', 'Bonne pratique'], rows: [
      ['La cliente est introuvable', 'Chercher par téléphone, puis la créer si besoin.'],
      ['Facture à faire pour une cliente', 'Créer la commande : la facture est automatique.'],
      ['Erreur dans une sortie ou une entrée de stock', 'Mouvements → Corriger. Ne jamais ressaisir à l’identique.'],
      ['« Veuillez spécifier la date de retrait »', 'Remplir la date de retrait avant de créer la commande.'],
      ['Commande abandonnée', 'Passer le statut en Annulé, ne pas supprimer.'],
      ['Doublon de cliente', 'Le signaler à la direction, ne pas supprimer.'],
      ['Message à toutes les clientes', 'Brouillon, test sur son numéro, validation de la direction, puis envoi.'],
    ] } },
    { p: 'Les rubriques **Rapports** et **Personnel** sont réservées à la direction. Pour toute situation non décrite ici, demandez avant d’agir.' },
  ],
};
